2024-04-25 13:30:15,630 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:30:16,228 [INFO] USER:ой helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00
2024-04-25 13:30:16,234 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\jsrc\main\java\com\helloworldtest.
2024-04-25 13:30:16,272 [INFO] USER:ой project_state.py:335:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world-test' to the pending ProjectState.
2024-04-25 13:30:16,273 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\src\lambdas.
2024-04-25 13:30:16,273 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\app\lambdas.
2024-04-25 13:30:16,273 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\swagger_src.
2024-04-25 13:30:16,294 [INFO] USER:ой java.py:30:assemble_java_mvn_lambdas LOG: Java sources are located by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/jsrc/main/java
2024-04-25 13:30:16,294 [INFO] USER:ой java.py:31:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test
2024-04-25 13:31:03,454 [INFO] USER:ой java.py:44:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2024-04-25 13:31:03,455 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:47.181204
2024-04-25 13:31:03,458 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:47.184198
2024-04-25 13:31:03,459 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:47.226491
2024-04-25 13:31:03,461 [INFO] USER:ой meta_processor.py:476:create_meta LOG: Bundle path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/bundles/hello_world-test_240425.133015
2024-04-25 13:31:03,490 [INFO] USER:ой helper.py:299:write_content_to_file LOG: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\.syndicate-config-dev/bundles/hello_world-test_240425.133015\build_meta.json file was created.
2024-04-25 13:31:03,491 [INFO] USER:ой helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.030006
2024-04-25 13:31:04,009 [INFO] USER:ой bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-04-25 13:31:09,088 [INFO] USER:ой helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:05.303056
2024-04-25 13:31:09,091 [INFO] USER:ой helper.py:336:timed LOG: Stage build, elapsed time: 0:00:53.175871
2024-04-25 13:31:43,922 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:31:44,332 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:31:44,332 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:31:44,527 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:31:44,527 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:31:44,666 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:31:44,666 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:31:44,859 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:31:44,859 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.133015
2024-04-25 13:31:45,011 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:31:45,011 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:31:45,194 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:31:45,386 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:31:45,386 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:31:45,569 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:31:46,023 [INFO] USER:ой deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 13:31:46,023 [INFO] USER:ой deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-04-25 13:31:46,820 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-04-25 13:31:47,457 [WARNING] USER:ой iam_resource.py:114:_create_policy_from_meta LOG: IAM policy cmtr-8937b1b4-lambda-basic-execution exists.
2024-04-25 13:31:47,608 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-04-25 13:31:47,767 [WARNING] USER:ой iam_resource.py:138:_create_role_from_meta LOG: IAM role cmtr-8937b1b4-hello_world-test-role exists.
2024-04-25 13:31:47,767 [INFO] USER:ой deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-04-25 13:31:48,087 [WARNING] USER:ой lambda_resource.py:277:_create_lambda_from_meta LOG: cmtr-8937b1b4-hello_world-test lambda exists.
2024-04-25 13:31:48,088 [INFO] USER:ой deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-04-25 13:31:48,089 [INFO] USER:ой deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-04-25 13:31:48,089 [INFO] USER:ой deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-04-25 13:31:48,091 [INFO] USER:ой deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-04-25 13:31:48,128 [INFO] USER:ой group_tagging_api_resource.py:61:apply_tags LOG: No tags are specified in config. Skipping...
2024-04-25 13:31:48,129 [INFO] USER:ой deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-04-25 13:31:48,272 [INFO] USER:ой bundle_processor.py:63:create_deploy_output LOG: Output file with name hello_world-test_240425.133015/outputs/hello-world-test.json has been created
2024-04-25 13:31:48,272 [INFO] USER:ой deployment_processor.py:364:create_deployment_resources LOG: Deploy output for hello-world-test was created.
2024-04-25 13:31:48,275 [INFO] USER:ой helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:02.449325
2024-04-25 13:31:48,571 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:31:48,571 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:31:49,150 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:35:50,855 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:35:51,264 [ERROR] USER:ой helper.py:103:wrapper LOG: Error occurred: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
2024-04-25 13:35:51,309 [ERROR] USER:ой helper.py:104:wrapper LOG: Traceback:
 Traceback (most recent call last):
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\helper.py", line 89, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\s3_connection.py", line 83, in put_object
    self.resource.Bucket(bucket).put_object(Body=file_obj,
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

2024-04-25 13:36:27,677 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:36:28,031 [ERROR] USER:ой helper.py:103:wrapper LOG: Error occurred: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
2024-04-25 13:36:28,032 [ERROR] USER:ой helper.py:104:wrapper LOG: Traceback:
 Traceback (most recent call last):
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\helper.py", line 89, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\s3_connection.py", line 83, in put_object
    self.resource.Bucket(bucket).put_object(Body=file_obj,
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

2024-04-25 13:37:53,562 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:37:53,988 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:37:53,988 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:37:54,194 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:37:54,194 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:37:54,361 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:37:54,362 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:37:54,558 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:37:54,558 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.133015
2024-04-25 13:37:54,709 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:37:54,709 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:37:54,880 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:37:55,052 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:37:55,052 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:37:55,238 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:37:55,349 [INFO] USER:ой deployment_processor.py:446:remove_deployment_resources LOG: Output file was loaded successfully
2024-04-25 13:37:55,350 [INFO] USER:ой deployment_processor.py:450:remove_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 13:37:55,350 [INFO] USER:ой deployment_processor.py:481:remove_deployment_resources LOG: Going to clean AWS resources
2024-04-25 13:37:55,350 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-04-25 13:37:57,231 [INFO] USER:ой iam_resource.py:82:_remove_role LOG: IAM role cmtr-8937b1b4-hello_world-test-role was removed.
2024-04-25 13:37:57,231 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_policy resources ...
2024-04-25 13:37:57,643 [INFO] USER:ой iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-8937b1b4-lambda-basic-execution was removed.
2024-04-25 13:37:57,644 [INFO] USER:ой deployment_processor.py:183:clean_resources LOG: Removing lambda resources ...
2024-04-25 13:37:58,571 [INFO] USER:ой lambda_resource.py:1004:_remove_lambda LOG: Lambda cmtr-8937b1b4-hello_world-test was removed.
2024-04-25 13:37:58,620 [WARNING] USER:ой bundle_processor.py:93:remove_failed_deploy_output LOG: Failed output file for deploy hello-world-test does not exist.
2024-04-25 13:37:58,621 [INFO] USER:ой helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:03.381477
2024-04-25 13:37:58,772 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:37:58,772 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:37:59,116 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:37:59,116 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:37:59,364 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:38:46,053 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:38:46,367 [INFO] USER:ой bundle_processor.py:207:create_bundles_bucket LOG: Bundles bucket syndicate-education-platform-custom-sandbox-artifacts-sbox01 already exists
2024-04-25 13:38:46,367 [INFO] USER:ой helper.py:336:timed LOG: Stage create_deploy_target_bucket, elapsed time: 0:00:00.314085
2024-04-25 13:38:55,536 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:38:56,094 [INFO] USER:ой helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.004151
2024-04-25 13:38:56,180 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\jsrc\main\java\com\helloworldtest.
2024-04-25 13:38:56,198 [INFO] USER:ой project_state.py:335:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world-test' to the pending ProjectState.
2024-04-25 13:38:56,198 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\src\lambdas.
2024-04-25 13:38:56,198 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\app\lambdas.
2024-04-25 13:38:56,198 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\swagger_src.
2024-04-25 13:38:56,241 [INFO] USER:ой java.py:30:assemble_java_mvn_lambdas LOG: Java sources are located by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/jsrc/main/java
2024-04-25 13:38:56,241 [INFO] USER:ой java.py:31:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test
2024-04-25 13:39:15,020 [INFO] USER:ой java.py:44:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2024-04-25 13:39:15,020 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:18.780203
2024-04-25 13:39:15,045 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:18.805170
2024-04-25 13:39:15,045 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:18.866138
2024-04-25 13:39:15,070 [INFO] USER:ой meta_processor.py:476:create_meta LOG: Bundle path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/bundles/hello_world-test_240425.133855
2024-04-25 13:39:15,088 [INFO] USER:ой helper.py:299:write_content_to_file LOG: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\.syndicate-config-dev/bundles/hello_world-test_240425.133855\build_meta.json file was created.
2024-04-25 13:39:15,088 [INFO] USER:ой helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.018989
2024-04-25 13:39:15,520 [INFO] USER:ой bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-04-25 13:39:20,480 [INFO] USER:ой helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:05.201900
2024-04-25 13:39:20,509 [INFO] USER:ой helper.py:336:timed LOG: Stage build, elapsed time: 0:00:24.784778
2024-04-25 13:39:26,505 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:39:26,961 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:39:26,961 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:39:27,161 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:39:27,161 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:39:27,307 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:39:27,307 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:39:27,492 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:39:27,492 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.133855
2024-04-25 13:39:27,645 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:39:27,645 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:39:27,838 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:39:28,005 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:39:28,005 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:39:28,203 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:39:28,588 [INFO] USER:ой deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 13:39:28,589 [INFO] USER:ой deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-04-25 13:39:28,887 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-04-25 13:39:29,603 [INFO] USER:ой iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-8937b1b4-lambda-basic-execution.
2024-04-25 13:39:29,807 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-04-25 13:39:33,250 [INFO] USER:ой iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-8937b1b4-hello_world-test-role.
2024-04-25 13:39:33,250 [INFO] USER:ой deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-04-25 13:39:34,665 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 13:39:37,605 [INFO] USER:ой deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-04-25 13:39:37,606 [INFO] USER:ой deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-04-25 13:39:37,607 [INFO] USER:ой deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-04-25 13:39:37,610 [INFO] USER:ой deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-04-25 13:39:37,621 [INFO] USER:ой group_tagging_api_resource.py:61:apply_tags LOG: No tags are specified in config. Skipping...
2024-04-25 13:39:37,621 [INFO] USER:ой deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-04-25 13:39:37,928 [INFO] USER:ой bundle_processor.py:63:create_deploy_output LOG: Output file with name hello_world-test_240425.133855/outputs/hello-world-test.json has been created
2024-04-25 13:39:37,928 [INFO] USER:ой deployment_processor.py:364:create_deployment_resources LOG: Deploy output for hello-world-test was created.
2024-04-25 13:39:37,931 [INFO] USER:ой helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:09.425732
2024-04-25 13:39:38,232 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:39:38,232 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:39:38,488 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:52:24,089 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:52:24,599 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:52:24,599 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:52:24,819 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:52:24,819 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:52:24,971 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:52:24,971 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:52:25,162 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:52:25,163 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.133855
2024-04-25 13:52:25,309 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:52:25,310 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:52:25,498 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:52:25,705 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:52:25,705 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:52:25,909 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:52:26,022 [INFO] USER:ой deployment_processor.py:446:remove_deployment_resources LOG: Output file was loaded successfully
2024-04-25 13:52:26,022 [INFO] USER:ой deployment_processor.py:450:remove_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 13:52:26,023 [INFO] USER:ой deployment_processor.py:481:remove_deployment_resources LOG: Going to clean AWS resources
2024-04-25 13:52:26,023 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-04-25 13:52:28,052 [INFO] USER:ой iam_resource.py:82:_remove_role LOG: IAM role cmtr-8937b1b4-hello_world-test-role was removed.
2024-04-25 13:52:28,053 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_policy resources ...
2024-04-25 13:52:28,427 [INFO] USER:ой iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-8937b1b4-lambda-basic-execution was removed.
2024-04-25 13:52:28,427 [INFO] USER:ой deployment_processor.py:183:clean_resources LOG: Removing lambda resources ...
2024-04-25 13:52:29,290 [INFO] USER:ой lambda_resource.py:1004:_remove_lambda LOG: Lambda cmtr-8937b1b4-hello_world-test was removed.
2024-04-25 13:52:29,343 [WARNING] USER:ой bundle_processor.py:93:remove_failed_deploy_output LOG: Failed output file for deploy hello-world-test does not exist.
2024-04-25 13:52:29,344 [INFO] USER:ой helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:03.433926
2024-04-25 13:52:29,444 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:52:29,445 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:52:29,867 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:52:29,867 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:52:30,067 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:00,921 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:53:01,305 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:01,306 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:01,512 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:01,513 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:53:01,694 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:01,694 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:01,897 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:01,898 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.133855
2024-04-25 13:53:41,251 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:53:41,691 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:41,691 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:41,875 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:41,875 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:53:42,033 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:42,034 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:42,214 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:42,214 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.133855
2024-04-25 13:53:42,391 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:42,391 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:42,587 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:42,772 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:42,772 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:42,951 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:53:42,997 [WARNING] USER:ой decorators.py:49:real_wrapper LOG: Output file already exists with name hello_world-test_240425.133855/outputs/hello-world-test.json. If it should be replaced with new one, use --replace_output flag.
2024-04-25 13:53:43,219 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:53:43,219 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:53:43,422 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:54:01,488 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:54:02,028 [INFO] USER:ой helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.001987
2024-04-25 13:54:02,063 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\jsrc\main\java\com\helloworldtest.
2024-04-25 13:54:02,242 [INFO] USER:ой project_state.py:335:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world-test' to the pending ProjectState.
2024-04-25 13:54:02,242 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\src\lambdas.
2024-04-25 13:54:02,242 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\app\lambdas.
2024-04-25 13:54:02,242 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\swagger_src.
2024-04-25 13:54:02,275 [INFO] USER:ой java.py:30:assemble_java_mvn_lambdas LOG: Java sources are located by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/jsrc/main/java
2024-04-25 13:54:02,275 [INFO] USER:ой java.py:31:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test
2024-04-25 13:54:23,002 [INFO] USER:ой java.py:44:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2024-04-25 13:54:23,003 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:20.729667
2024-04-25 13:54:23,055 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:20.781636
2024-04-25 13:54:23,055 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:20.991967
2024-04-25 13:54:23,104 [INFO] USER:ой meta_processor.py:476:create_meta LOG: Bundle path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/bundles/hello_world-test_240425.135401
2024-04-25 13:54:23,116 [INFO] USER:ой helper.py:299:write_content_to_file LOG: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\.syndicate-config-dev/bundles/hello_world-test_240425.135401\build_meta.json file was created.
2024-04-25 13:54:23,117 [INFO] USER:ой helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.012990
2024-04-25 13:54:23,585 [INFO] USER:ой bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-04-25 13:54:28,490 [INFO] USER:ой helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:05.137455
2024-04-25 13:54:28,545 [INFO] USER:ой helper.py:336:timed LOG: Stage build, elapsed time: 0:00:26.800297
2024-04-25 13:54:35,063 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:54:35,503 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:54:35,504 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:54:35,732 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:54:35,732 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:54:35,884 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:54:35,884 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:54:36,123 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:54:36,123 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.135401
2024-04-25 13:54:36,262 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:54:36,262 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:54:36,488 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:54:36,662 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:54:36,663 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:54:36,876 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:54:37,181 [INFO] USER:ой deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 13:54:37,181 [INFO] USER:ой deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-04-25 13:54:37,518 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-04-25 13:54:38,231 [INFO] USER:ой iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-8937b1b4-lambda-basic-execution.
2024-04-25 13:54:38,393 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-04-25 13:54:41,608 [INFO] USER:ой iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-8937b1b4-hello_world-test-role.
2024-04-25 13:54:41,608 [INFO] USER:ой deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-04-25 13:54:42,966 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 13:54:44,518 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 13:54:50,413 [INFO] USER:ой deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-04-25 13:54:50,414 [INFO] USER:ой deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-04-25 13:54:50,414 [INFO] USER:ой deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-04-25 13:54:50,416 [INFO] USER:ой deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-04-25 13:54:50,425 [INFO] USER:ой group_tagging_api_resource.py:61:apply_tags LOG: No tags are specified in config. Skipping...
2024-04-25 13:54:50,427 [INFO] USER:ой deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-04-25 13:54:50,711 [INFO] USER:ой bundle_processor.py:63:create_deploy_output LOG: Output file with name hello_world-test_240425.135401/outputs/hello-world-test.json has been created
2024-04-25 13:54:50,711 [INFO] USER:ой deployment_processor.py:364:create_deployment_resources LOG: Deploy output for hello-world-test was created.
2024-04-25 13:54:50,714 [INFO] USER:ой helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:13.584983
2024-04-25 13:54:50,933 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:54:50,933 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:54:51,137 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:55:01,329 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:55:01,823 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:55:01,823 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:55:02,039 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:55:02,040 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:55:02,178 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:55:02,178 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:55:02,426 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:55:02,426 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.135401
2024-04-25 13:59:29,031 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 13:59:29,627 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:59:29,628 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:59:29,886 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:59:29,886 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 13:59:30,038 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:59:30,038 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:59:30,579 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:59:30,579 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.135401
2024-04-25 13:59:30,742 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:59:30,742 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:59:30,985 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:59:31,202 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:59:31,202 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:59:31,538 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 13:59:31,638 [INFO] USER:ой deployment_processor.py:446:remove_deployment_resources LOG: Output file was loaded successfully
2024-04-25 13:59:31,638 [INFO] USER:ой deployment_processor.py:450:remove_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 13:59:31,638 [INFO] USER:ой deployment_processor.py:481:remove_deployment_resources LOG: Going to clean AWS resources
2024-04-25 13:59:31,639 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-04-25 13:59:33,772 [INFO] USER:ой iam_resource.py:82:_remove_role LOG: IAM role cmtr-8937b1b4-hello_world-test-role was removed.
2024-04-25 13:59:33,773 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_policy resources ...
2024-04-25 13:59:34,196 [INFO] USER:ой iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-8937b1b4-lambda-basic-execution was removed.
2024-04-25 13:59:34,197 [INFO] USER:ой deployment_processor.py:183:clean_resources LOG: Removing lambda resources ...
2024-04-25 13:59:35,149 [INFO] USER:ой lambda_resource.py:1004:_remove_lambda LOG: Lambda cmtr-8937b1b4-hello_world-test was removed.
2024-04-25 13:59:35,202 [WARNING] USER:ой bundle_processor.py:93:remove_failed_deploy_output LOG: Failed output file for deploy hello-world-test does not exist.
2024-04-25 13:59:35,203 [INFO] USER:ой helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:03.665430
2024-04-25 13:59:35,328 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:59:35,328 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:59:35,710 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 13:59:35,710 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 13:59:35,938 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:00:37,009 [WARNING] USER:ой validator.py:175:validate LOG: Unknown parameter(s) in the configuration file: {'deployments'}
2024-04-25 14:00:37,306 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:00:37,877 [INFO] USER:ой helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.002990
2024-04-25 14:00:37,951 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\jsrc\main\java\com\helloworldtest.
2024-04-25 14:00:37,975 [INFO] USER:ой project_state.py:335:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world-test' to the pending ProjectState.
2024-04-25 14:00:37,975 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\src\lambdas.
2024-04-25 14:00:37,976 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\app\lambdas.
2024-04-25 14:00:37,976 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\swagger_src.
2024-04-25 14:00:38,397 [INFO] USER:ой java.py:30:assemble_java_mvn_lambdas LOG: Java sources are located by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/jsrc/main/java
2024-04-25 14:00:38,397 [INFO] USER:ой java.py:31:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test
2024-04-25 14:01:00,577 [INFO] USER:ой java.py:44:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2024-04-25 14:01:00,579 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:22.553689
2024-04-25 14:01:00,628 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:22.602658
2024-04-25 14:01:00,629 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:22.678537
2024-04-25 14:01:00,708 [INFO] USER:ой meta_processor.py:476:create_meta LOG: Bundle path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/bundles/hello_world-test_240425.140037
2024-04-25 14:01:00,731 [INFO] USER:ой helper.py:299:write_content_to_file LOG: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\.syndicate-config-dev/bundles/hello_world-test_240425.140037\build_meta.json file was created.
2024-04-25 14:01:00,731 [INFO] USER:ой helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.022987
2024-04-25 14:01:01,117 [INFO] USER:ой bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-04-25 14:01:06,183 [INFO] USER:ой helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:05.255283
2024-04-25 14:01:06,228 [INFO] USER:ой helper.py:336:timed LOG: Stage build, elapsed time: 0:00:28.667981
2024-04-25 14:01:25,618 [WARNING] USER:ой validator.py:175:validate LOG: Unknown parameter(s) in the configuration file: {'deployments'}
2024-04-25 14:01:25,837 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:01:26,227 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:26,227 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:26,422 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:01:26,423 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 14:01:26,594 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:26,594 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:26,822 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:01:26,822 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.140037
2024-04-25 14:01:40,755 [WARNING] USER:ой validator.py:175:validate LOG: Unknown parameter(s) in the configuration file: {'deployments'}
2024-04-25 14:01:40,957 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:01:41,458 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:41,458 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:41,694 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:01:41,772 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 14:01:41,939 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:41,940 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:42,135 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:01:42,136 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.140037
2024-04-25 14:01:42,306 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:42,306 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:42,496 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:01:42,760 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:42,760 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:43,026 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:01:43,307 [INFO] USER:ой deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 14:01:43,308 [INFO] USER:ой deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-04-25 14:01:43,574 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-04-25 14:01:44,347 [INFO] USER:ой iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-8937b1b4-lambda-basic-execution.
2024-04-25 14:01:44,511 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-04-25 14:01:48,072 [INFO] USER:ой iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-8937b1b4-hello_world-test-role.
2024-04-25 14:01:48,072 [INFO] USER:ой deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-04-25 14:01:49,691 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 14:01:51,242 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 14:01:57,318 [INFO] USER:ой deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-04-25 14:01:57,319 [INFO] USER:ой deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-04-25 14:01:57,319 [INFO] USER:ой deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-04-25 14:01:57,322 [INFO] USER:ой deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-04-25 14:01:57,337 [INFO] USER:ой group_tagging_api_resource.py:61:apply_tags LOG: No tags are specified in config. Skipping...
2024-04-25 14:01:57,338 [INFO] USER:ой deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-04-25 14:01:57,653 [INFO] USER:ой bundle_processor.py:63:create_deploy_output LOG: Output file with name hello_world-test_240425.140037/outputs/hello-world-test.json has been created
2024-04-25 14:01:57,654 [INFO] USER:ой deployment_processor.py:364:create_deployment_resources LOG: Deploy output for hello-world-test was created.
2024-04-25 14:01:57,656 [INFO] USER:ой helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:14.401278
2024-04-25 14:01:57,885 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:01:57,885 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:01:58,107 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:02:00,883 [WARNING] USER:ой validator.py:175:validate LOG: Unknown parameter(s) in the configuration file: {'deployments'}
2024-04-25 14:02:01,171 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:02:01,651 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:02:01,651 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:02:01,867 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:02:01,868 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 14:02:02,064 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:02:02,064 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:02:02,265 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:02:02,265 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.140037
2024-04-25 14:05:46,443 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:05:46,936 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:05:46,937 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:05:47,147 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:05:47,147 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 14:05:47,320 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:05:47,320 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:05:47,535 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:05:47,535 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.140037
2024-04-25 14:24:42,584 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:24:43,191 [ERROR] USER:ой helper.py:103:wrapper LOG: Error occurred: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
2024-04-25 14:24:43,197 [ERROR] USER:ой helper.py:104:wrapper LOG: Traceback:
 Traceback (most recent call last):
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\helper.py", line 89, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\s3_connection.py", line 83, in put_object
    self.resource.Bucket(bucket).put_object(Body=file_obj,
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

2024-04-25 14:38:19,377 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:38:19,827 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:38:19,827 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:38:20,139 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:38:20,140 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 14:38:20,291 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:38:20,291 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:38:20,510 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:38:20,510 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.140037
2024-04-25 14:38:20,653 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:38:20,653 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:38:20,864 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:38:21,064 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:38:21,064 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:38:21,266 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:38:21,380 [INFO] USER:ой deployment_processor.py:446:remove_deployment_resources LOG: Output file was loaded successfully
2024-04-25 14:38:21,380 [INFO] USER:ой deployment_processor.py:450:remove_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 14:38:21,381 [INFO] USER:ой deployment_processor.py:481:remove_deployment_resources LOG: Going to clean AWS resources
2024-04-25 14:38:21,382 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-04-25 14:38:23,400 [INFO] USER:ой iam_resource.py:82:_remove_role LOG: IAM role cmtr-8937b1b4-hello_world-test-role was removed.
2024-04-25 14:38:23,401 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_policy resources ...
2024-04-25 14:38:23,762 [INFO] USER:ой iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-8937b1b4-lambda-basic-execution was removed.
2024-04-25 14:38:23,762 [INFO] USER:ой deployment_processor.py:183:clean_resources LOG: Removing lambda resources ...
2024-04-25 14:38:24,616 [INFO] USER:ой lambda_resource.py:1004:_remove_lambda LOG: Lambda cmtr-8937b1b4-hello_world-test was removed.
2024-04-25 14:38:24,668 [WARNING] USER:ой bundle_processor.py:93:remove_failed_deploy_output LOG: Failed output file for deploy hello-world-test does not exist.
2024-04-25 14:38:24,671 [INFO] USER:ой helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:03.405096
2024-04-25 14:38:24,798 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:38:24,798 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:38:25,178 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:38:25,178 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:38:25,382 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:38:31,519 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:38:32,058 [INFO] USER:ой helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.003983
2024-04-25 14:38:32,117 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\jsrc\main\java\com\helloworldtest.
2024-04-25 14:38:32,118 [INFO] USER:ой project_state.py:335:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world-test' to the pending ProjectState.
2024-04-25 14:38:32,118 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\src\lambdas.
2024-04-25 14:38:32,119 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\app\lambdas.
2024-04-25 14:38:32,119 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\swagger_src.
2024-04-25 14:38:32,180 [INFO] USER:ой java.py:30:assemble_java_mvn_lambdas LOG: Java sources are located by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/jsrc/main/java
2024-04-25 14:38:32,180 [INFO] USER:ой java.py:31:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test
2024-04-25 14:38:58,190 [INFO] USER:ой java.py:44:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2024-04-25 14:38:58,191 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:26.032239
2024-04-25 14:38:58,232 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:26.073214
2024-04-25 14:38:58,232 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:26.115197
2024-04-25 14:38:58,274 [INFO] USER:ой meta_processor.py:476:create_meta LOG: Bundle path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/bundles/hello_world-test_240425.143831
2024-04-25 14:38:58,278 [INFO] USER:ой helper.py:299:write_content_to_file LOG: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\.syndicate-config-dev/bundles/hello_world-test_240425.143831\build_meta.json file was created.
2024-04-25 14:38:58,278 [INFO] USER:ой helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.004997
2024-04-25 14:38:58,738 [INFO] USER:ой bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-04-25 14:39:04,017 [INFO] USER:ой helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:05.530067
2024-04-25 14:39:04,051 [INFO] USER:ой helper.py:336:timed LOG: Stage build, elapsed time: 0:00:32.292657
2024-04-25 14:39:27,730 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 14:39:28,125 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:39:28,126 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:39:28,348 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:39:28,349 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 14:39:28,537 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:39:28,537 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:39:28,751 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:39:28,752 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.143831
2024-04-25 14:39:28,917 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:39:28,918 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:39:29,116 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:39:29,320 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:39:29,320 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:39:29,520 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 14:39:29,787 [INFO] USER:ой deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 14:39:29,787 [INFO] USER:ой deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-04-25 14:39:30,084 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-04-25 14:39:30,821 [INFO] USER:ой iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-8937b1b4-lambda-basic-execution.
2024-04-25 14:39:30,985 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-04-25 14:39:34,501 [INFO] USER:ой iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-8937b1b4-hello_world-test-role.
2024-04-25 14:39:34,502 [INFO] USER:ой deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-04-25 14:39:35,866 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 14:39:37,429 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 14:39:43,455 [INFO] USER:ой deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-04-25 14:39:43,456 [INFO] USER:ой deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-04-25 14:39:43,456 [INFO] USER:ой deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-04-25 14:39:43,467 [INFO] USER:ой deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-04-25 14:39:43,477 [INFO] USER:ой group_tagging_api_resource.py:61:apply_tags LOG: No tags are specified in config. Skipping...
2024-04-25 14:39:43,478 [INFO] USER:ой deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-04-25 14:39:43,726 [INFO] USER:ой bundle_processor.py:63:create_deploy_output LOG: Output file with name hello_world-test_240425.143831/outputs/hello-world-test.json has been created
2024-04-25 14:39:43,727 [INFO] USER:ой deployment_processor.py:364:create_deployment_resources LOG: Deploy output for hello-world-test was created.
2024-04-25 14:39:43,733 [INFO] USER:ой helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:13.997955
2024-04-25 14:39:44,030 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 14:39:44,030 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 14:39:44,275 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:25:12,297 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 16:25:12,781 [ERROR] USER:ой helper.py:103:wrapper LOG: Error occurred: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
2024-04-25 16:25:12,788 [ERROR] USER:ой helper.py:104:wrapper LOG: Traceback:
 Traceback (most recent call last):
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\helper.py", line 89, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\syndicate\connection\s3_connection.py", line 83, in put_object
    self.resource.Bucket(bucket).put_object(Body=file_obj,
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\ой\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

2024-04-25 16:25:54,005 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 16:25:54,459 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:25:54,459 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:25:54,698 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:25:54,698 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 16:25:54,857 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:25:54,857 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:25:55,174 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:25:55,174 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.143831
2024-04-25 16:25:55,360 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:25:55,360 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:25:55,599 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:25:55,838 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:25:55,839 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:25:56,112 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:25:56,238 [INFO] USER:ой deployment_processor.py:446:remove_deployment_resources LOG: Output file was loaded successfully
2024-04-25 16:25:56,238 [INFO] USER:ой deployment_processor.py:450:remove_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 16:25:56,238 [INFO] USER:ой deployment_processor.py:481:remove_deployment_resources LOG: Going to clean AWS resources
2024-04-25 16:25:56,239 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-04-25 16:25:58,274 [INFO] USER:ой iam_resource.py:82:_remove_role LOG: IAM role cmtr-8937b1b4-hello_world-test-role was removed.
2024-04-25 16:25:58,275 [INFO] USER:ой deployment_processor.py:176:clean_resources LOG: Removing iam_policy resources ...
2024-04-25 16:25:58,655 [INFO] USER:ой iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-8937b1b4-lambda-basic-execution was removed.
2024-04-25 16:25:58,656 [INFO] USER:ой deployment_processor.py:183:clean_resources LOG: Removing lambda resources ...
2024-04-25 16:25:59,498 [INFO] USER:ой lambda_resource.py:1004:_remove_lambda LOG: Lambda cmtr-8937b1b4-hello_world-test was removed.
2024-04-25 16:25:59,546 [WARNING] USER:ой bundle_processor.py:93:remove_failed_deploy_output LOG: Failed output file for deploy hello-world-test does not exist.
2024-04-25 16:25:59,547 [INFO] USER:ой helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:03.435027
2024-04-25 16:25:59,674 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:25:59,675 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:00,085 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:26:00,086 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:00,332 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:26:05,895 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 16:26:06,326 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:26:06,326 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:06,619 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:26:06,619 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 16:26:06,785 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:26:06,785 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:07,025 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:26:07,025 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.143831
2024-04-25 16:26:07,185 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:26:07,185 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:07,437 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:26:07,720 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:26:07,720 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:07,980 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:26:08,026 [WARNING] USER:ой decorators.py:49:real_wrapper LOG: Output file already exists with name hello_world-test_240425.143831/outputs/hello-world-test.json. If it should be replaced with new one, use --replace_output flag.
2024-04-25 16:26:08,222 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:26:08,222 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:26:08,483 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:26:44,632 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 16:26:45,098 [INFO] USER:ой helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000999
2024-04-25 16:26:45,147 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\jsrc\main\java\com\helloworldtest.
2024-04-25 16:26:45,147 [INFO] USER:ой project_state.py:335:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world-test' to the pending ProjectState.
2024-04-25 16:26:45,148 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\src\lambdas.
2024-04-25 16:26:45,148 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\app\lambdas.
2024-04-25 16:26:45,148 [INFO] USER:ой project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\hello_world-test\swagger_src.
2024-04-25 16:26:45,196 [INFO] USER:ой java.py:30:assemble_java_mvn_lambdas LOG: Java sources are located by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/jsrc/main/java
2024-04-25 16:26:45,196 [INFO] USER:ой java.py:31:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test
2024-04-25 16:27:14,880 [INFO] USER:ой java.py:44:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2024-04-25 16:27:14,880 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:29.685540
2024-04-25 16:27:14,930 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:29.735521
2024-04-25 16:27:14,931 [INFO] USER:ой helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:29.785482
2024-04-25 16:27:14,974 [INFO] USER:ой meta_processor.py:476:create_meta LOG: Bundle path: H:/IntellijIDEAprojects/AWS_course/lambda2/task02/hello_world-test/bundles/hello_world-test_240425.162644
2024-04-25 16:27:15,223 [INFO] USER:ой helper.py:299:write_content_to_file LOG: H:\IntellijIDEAprojects\AWS_course\lambda2\task02\.syndicate-config-dev/bundles/hello_world-test_240425.162644\build_meta.json file was created.
2024-04-25 16:27:15,224 [INFO] USER:ой helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.250856
2024-04-25 16:27:15,675 [INFO] USER:ой bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-04-25 16:27:20,598 [INFO] USER:ой helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:05.128733
2024-04-25 16:27:20,642 [INFO] USER:ой helper.py:336:timed LOG: Stage build, elapsed time: 0:00:35.803722
2024-04-25 16:27:26,825 [INFO] USER:ой processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-04-25 16:27:27,274 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:27:27,274 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:27:27,551 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:27:27,551 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: hello-world-test
2024-04-25 16:27:27,732 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:27:27,732 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:27:27,975 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:27:27,976 [INFO] USER:ой helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: hello_world-test_240425.162644
2024-04-25 16:27:28,158 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:27:28,158 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:27:28,411 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:27:28,649 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:27:28,649 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:27:28,892 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-04-25 16:27:29,163 [INFO] USER:ой deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-04-25 16:27:29,163 [INFO] USER:ой deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-04-25 16:27:29,564 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-04-25 16:27:30,335 [INFO] USER:ой iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-8937b1b4-lambda-basic-execution.
2024-04-25 16:27:30,512 [INFO] USER:ой deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-04-25 16:27:33,988 [INFO] USER:ой iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-8937b1b4-hello_world-test-role.
2024-04-25 16:27:33,988 [INFO] USER:ой deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-04-25 16:27:35,467 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 16:27:37,065 [ERROR] USER:ой helper.py:94:wrapper LOG: Retry on create_lambda. Error: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2024-04-25 16:27:42,414 [INFO] USER:ой deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-04-25 16:27:42,414 [INFO] USER:ой deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-04-25 16:27:42,414 [INFO] USER:ой deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-04-25 16:27:42,415 [INFO] USER:ой deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-04-25 16:27:42,421 [INFO] USER:ой group_tagging_api_resource.py:61:apply_tags LOG: No tags are specified in config. Skipping...
2024-04-25 16:27:42,422 [INFO] USER:ой deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-04-25 16:27:42,682 [INFO] USER:ой bundle_processor.py:63:create_deploy_output LOG: Output file with name hello_world-test_240425.162644/outputs/hello-world-test.json has been created
2024-04-25 16:27:42,682 [INFO] USER:ой deployment_processor.py:364:create_deployment_resources LOG: Deploy output for hello-world-test was created.
2024-04-25 16:27:42,684 [INFO] USER:ой helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:13.590819
2024-04-25 16:27:42,953 [INFO] USER:ой project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-04-25 16:27:42,953 [INFO] USER:ой project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-04-25 16:27:43,211 [INFO] USER:ой sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
